# Generated by Django 3.2.7 on 2021-12-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0024_auto_20211127_2120'),
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='AssociatedPost',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Base.post'),
            preserve_default=False,
        ),
    ]
