# Generated by Django 3.2.7 on 2021-12-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0025_alter_post_bookcoverimage'),
        ('Images', '0002_photos_associatedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='AssociatedPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.post', unique=True),
        ),
    ]
