# Generated by Django 3.2.7 on 2021-10-12 19:37

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('excerpt', models.TextField()),
                ('BookCoverImage', models.FileField(upload_to='uploads/CoverImage')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('ClosingTime', models.DateTimeField(default=datetime.datetime(2021, 10, 22, 19, 37, 13, 359013, tzinfo=utc))),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('notClosed', 'NotClosed')], default='request', max_length=10)),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Base.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('AssociatedPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.post')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='SubjectiveResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.subjectivequestion')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.objectivequestion')),
            ],
        ),
        migrations.AddField(
            model_name='objectivequestion',
            name='AssociatedPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.post'),
        ),
    ]
