# Generated by Django 3.2.7 on 2021-10-12 19:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ClosingTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 19, 51, 55, 273167, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='SubscribedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAprooved', models.BooleanField(default=False)),
                ('AssociatedPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
