# Generated by Django 3.2.7 on 2021-10-14 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_auto_20211015_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='subjective', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='ClosingTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 18, 40, 35, 12426, tzinfo=utc)),
        ),
    ]
