# Generated by Django 3.2.7 on 2021-10-21 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_auto_20211015_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ClosingTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 9, 56, 58, 907880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('notClosed', 'NotClosed')], default='notClosed', max_length=10),
        ),
    ]
