# Generated by Django 3.2.7 on 2021-10-28 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_auto_20211021_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedposts',
            name='Age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribedposts',
            name='ReviewedPosts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribedposts',
            name='Sex',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribedposts',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='ClosingTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 17, 7, 3, 417338, tzinfo=utc)),
        ),
    ]
