# Generated by Django 3.2.7 on 2021-10-28 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_auto_20211028_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribedposts',
            name='ImageLink',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribedposts',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='ClosingTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 17, 11, 26, 585211, tzinfo=utc)),
        ),
    ]
