# Generated by Django 3.1.6 on 2021-11-05 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_auto_20211105_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='PostNumber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Base.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='ClosingTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 17, 3, 54, 326659, tzinfo=utc)),
        ),
    ]
