# Generated by Django 3.2.7 on 2021-11-24 09:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0015_auto_20211124_0015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribedposts',
            unique_together={('AssociatedPost', 'User')},
        ),
    ]
