# Generated by Django 3.2.7 on 2021-11-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_post_postdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='PostData',
        ),
    ]
