# Generated by Django 3.2.7 on 2021-11-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0018_remove_post_postdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PostData',
            field=models.FileField(default=0, upload_to='uploads/PostData'),
        ),
    ]
