# Generated by Django 3.2.7 on 2021-11-27 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0020_auto_20211126_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedposts',
            name='reiewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('question', 'User')},
        ),
    ]
