# Generated by Django 3.2.7 on 2021-11-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0021_auto_20211127_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribedposts',
            old_name='reiewed',
            new_name='reviewed',
        ),
    ]
