# Generated by Django 3.2.7 on 2021-12-03 17:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0024_auto_20211127_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='BookCoverImage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
