# Generated by Django 3.2.7 on 2022-02-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0025_alter_post_bookcoverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostData',
            field=models.URLField(max_length=500),
        ),
    ]
